"""Explicit policy marker: opaque analyst/consensus forecasts are excluded from v0.8.1 automatic evidence."""

ANALYST_FORECAST_AUTOMATIC_EVIDENCE_ENABLED = False
ANALYST_FORECAST_EXCLUSION_REASON = "EXTERNAL_FORECAST_METHOD_NOT_VALIDATED"

__all__ = ["ANALYST_FORECAST_AUTOMATIC_EVIDENCE_ENABLED", "ANALYST_FORECAST_EXCLUSION_REASON"]
